#!/usr/bin/env python3
# Copyright (C) 2026 NuzLike contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build the shared Rust engine and a self-contained offline browser patcher."""
from __future__ import annotations

import base64
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(*args: str) -> None:
    subprocess.run(args, cwd=ROOT, check=True)


def main() -> None:
    version = (ROOT / "VERSION").read_text().strip()
    run("cargo", "build", "--locked", "--manifest-path", "src-tauri/Cargo.toml", "--lib",
        "--release", "--target", "wasm32-unknown-unknown", "--no-default-features", "--features", "web")
    engine = ROOT / "ui/engine"
    engine.mkdir(parents=True, exist_ok=True)
    run("wasm-bindgen", "--target", "web", "--out-dir", str(engine), "--out-name", "nuzlike",
        "src-tauri/target/wasm32-unknown-unknown/release/nuzlike_patcher_app_lib.wasm")
    wasm = (engine / "nuzlike_bg.wasm").read_bytes()
    (engine / "wasm-bytes.ts").write_text(
        "// Generated by tools/build_web.py; do not edit.\nexport const wasmBase64 = "
        + json.dumps(base64.b64encode(wasm).decode("ascii")) + ";\n"
    )
    run("npm", "run", "ui:build", "--", "--mode", "web")
    output = ROOT / "ui-dist"
    html = (output / "index.html").read_text()

    def script(match: re.Match[str]) -> str:
        source = (output / match[1].removeprefix("./")).read_text()
        return '<script type="module">' + source.replace("</script", "<\\/script") + "</script>"

    def style(match: re.Match[str]) -> str:
        source = (output / match[1].removeprefix("./")).read_text()
        return "<style>" + source + "</style>"

    html = re.sub(r'<script type="module"[^>]*src="([^"]+)"[^>]*></script>', script, html)
    html = re.sub(r'<link rel="stylesheet"[^>]*href="([^"]+)"[^>]*>', style, html)
    if re.search(r'<(?:script|link)[^>]*(?:src|href)=', html):
        raise RuntimeError("Offline HTML still references an external script or stylesheet")
    # No page connection is needed, including while processing a selected ROM.
    policy = "default-src 'none'; script-src 'unsafe-inline' 'wasm-unsafe-eval' blob:; style-src 'unsafe-inline'; worker-src blob:; img-src data:; connect-src 'none'; base-uri 'none'; form-action 'none'"
    html = html.replace('<meta charset="UTF-8" />', '<meta charset="UTF-8" />\n    <meta http-equiv="Content-Security-Policy" content="' + policy + '" />')
    (output / "index.html").write_text(html)
    name = f"nuzlike-{version}-offline.html"
    (output / name).write_text(html)
    (output / ".nojekyll").touch()
    (output / "version.json").write_text(json.dumps({
        "version": version,
        "source_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
        "source_dirty": bool(subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True).strip()),
        "html_sha256": hashlib.sha256(html.encode()).hexdigest(),
        "wasm_sha256": hashlib.sha256(wasm).hexdigest(),
        "offline_file": name,
    }, indent=2) + "\n")
    print(f"Built {name}: {len(html.encode()):,} bytes; all processing stays on device")


if __name__ == "__main__":
    main()
