// Copyright (C) 2026 NuzLike contributors
// SPDX-License-Identifier: GPL-3.0-or-later
// @ts-ignore Generated by tools/build_web.py; absent in native-only checkouts.
import init, { catalog, inspect, patch, compose, analyze } from "./engine/nuzlike.js";
// @ts-ignore Generated by tools/build_web.py; absent in native-only checkouts.
import { wasmBase64 } from "./engine/wasm-bytes";

const ready = init({ module_or_path: Uint8Array.from(atob(wasmBase64), c => c.charCodeAt(0)) });
self.onmessage = async ({ data }: MessageEvent<{ id: number; command: string; bytes?: Uint8Array }>) => {
  try {
    await ready;
    const bytes = data.bytes ?? new Uint8Array();
    let result: unknown;
    switch (data.command) {
      case "get_catalog": result = JSON.parse(catalog()); break;
      case "inspect_rom": result = JSON.parse(inspect(bytes)); break;
      case "patch_rom": result = patch(bytes).buffer; break;
      case "compose_randomized_rom": result = compose(bytes).buffer; break;
      case "analyze_randomized_rom": result = analyze(bytes).buffer; break;
      default: throw new Error("Unsupported browser operation.");
    }
    self.postMessage({ id: data.id, result }, { transfer: result instanceof ArrayBuffer ? [result] : [] });
  } catch (error) {
    self.postMessage({ id: data.id, error: String(error) });
  }
};
